name: test cpu ram

on: 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test cpu ram neofetch
        run: |
          sudo apt update -y
          sudo apt install neofetch -y
          neofetch
          lscpu
          free -h
          lsblk
          ls /mnt
          df -h
          systemctl
